---
description: Auto-Skill Router and Manifest for AZURE DEVELOPER
globs: *
---

# 🦸 Auto-Skill Router (AZURE DEVELOPER)

As a **AZURE DEVELOPER**, you must **proactively** consult relevant local skill and agent documentation when the user asks for help, even without explicit slash commands.

## 🗂️ Available Skills Library
Below is the index of available skills for your persona. When a user's intent matches one of these descriptions, you MUST explicitly read the corresponding `SKILL.md` file to load its instructions.

- **azd-deployment**: ""Deploy containerized applications to Azure Container Apps using Azure Developer CLI (azd). Use when setting up azd projects, writing azure.yaml configuration, creating Bicep infrastructure for Cont...""
- **azure-ai-agents-persistent-dotnet**: "Azure AI Agents Persistent SDK for .NET. Low-level SDK for creating and managing AI agents with threads, messages, runs, and tools."
- **azure-ai-agents-persistent-java**: "Azure AI Agents Persistent SDK for Java. Low-level SDK for creating and managing AI agents with threads, messages, runs, and tools."
- **azure-ai-anomalydetector-java**: ""Build anomaly detection applications with Azure AI Anomaly Detector SDK for Java. Use when implementing univariate/multivariate anomaly detection, time-series analysis, or AI-powered monitoring.""
- **azure-ai-contentsafety-java**: ""Build content moderation applications with Azure AI Content Safety SDK for Java. Use when implementing text/image analysis, blocklist management, or harm detection for hate, violence, sexual conten...""
- **azure-ai-contentsafety-py**: "Azure AI Content Safety SDK for Python. Use for detecting harmful content in text and images with multi-severity classification."
- **azure-ai-contentsafety-ts**: ""Analyze text and images for harmful content using Azure AI Content Safety (@azure-rest/ai-content-safety). Use when moderating user-generated content, detecting hate speech, violence, sexual conten...""
- **azure-ai-contentunderstanding-py**: "Azure AI Content Understanding SDK for Python. Use for multimodal content extraction from documents, images, audio, and video."
- **azure-ai-document-intelligence-dotnet**: "Azure AI Document Intelligence SDK for .NET. Extract text, tables, and structured data from documents using prebuilt and custom models."
- **azure-ai-document-intelligence-ts**: ""Extract text, tables, and structured data from documents using Azure Document Intelligence (@azure-rest/ai-document-intelligence). Use when processing invoices, receipts, IDs, forms, or building cu...""
- **azure-ai-formrecognizer-java**: ""Build document analysis applications with Azure Document Intelligence (Form Recognizer) SDK for Java. Use when extracting text, tables, key-value pairs from documents, receipts, invoices, or buildi...""
- **azure-ai-ml-py**: "Azure Machine Learning SDK v2 for Python. Use for ML workspaces, jobs, models, datasets, compute, and pipelines."
- **azure-ai-openai-dotnet**: "Azure OpenAI SDK for .NET. Client library for Azure OpenAI and OpenAI services. Use for chat completions, embeddings, image generation, audio transcription, and assistants."
- **azure-ai-projects-dotnet**: "Azure AI Projects SDK for .NET. High-level client for Azure AI Foundry projects including agents, connections, datasets, deployments, evaluations, and indexes."
- **azure-ai-projects-java**: "Azure AI Projects SDK for Java. High-level SDK for Azure AI Foundry project management including connections, datasets, indexes, and evaluations."
- **azure-ai-projects-py**: ""Build AI applications using the Azure AI Projects Python SDK (azure-ai-projects). Use when working with Foundry project clients, creating versioned agents with PromptAgentDefinition, running evalua...""
- **azure-ai-projects-ts**: ""Build AI applications using Azure AI Projects SDK for JavaScript (@azure/ai-projects). Use when working with Foundry project clients, agents, connections, deployments, datasets, indexes, evaluation...""
- **azure-ai-textanalytics-py**: "Azure AI Text Analytics SDK for sentiment analysis, entity recognition, key phrases, language detection, PII, and healthcare NLP. Use for natural language processing on text."
- **azure-ai-transcription-py**: "Azure AI Transcription SDK for Python. Use for real-time and batch speech-to-text transcription with timestamps and diarization."
- **azure-ai-translation-document-py**: "Azure AI Document Translation SDK for batch translation of documents with format preservation. Use for translating Word, PDF, Excel, PowerPoint, and other document formats at scale."
- **azure-ai-translation-text-py**: "Azure AI Text Translation SDK for real-time text translation, transliteration, language detection, and dictionary lookup. Use for translating text content in applications."
- **azure-ai-translation-ts**: ""Build translation applications using Azure Translation SDKs for JavaScript (@azure-rest/ai-translation-text, @azure-rest/ai-translation-document). Use when implementing text translation, transliter...""
- **azure-ai-vision-imageanalysis-java**: ""Build image analysis applications with Azure AI Vision SDK for Java. Use when implementing image captioning, OCR text extraction, object detection, tagging, or smart cropping.""
- **azure-ai-vision-imageanalysis-py**: "Azure AI Vision Image Analysis SDK for captions, tags, objects, OCR, people detection, and smart cropping. Use for computer vision and image understanding tasks."
- **azure-ai-voicelive-dotnet**: "Azure AI Voice Live SDK for .NET. Build real-time voice AI applications with bidirectional WebSocket communication."
- **azure-ai-voicelive-java**: "Azure AI VoiceLive SDK for Java. Real-time bidirectional voice conversations with AI assistants using WebSocket."
- **azure-ai-voicelive-py**: ""Build real-time voice AI applications using Azure AI Voice Live SDK (azure-ai-voicelive). Use this skill when creating Python applications that need real-time bidirectional audio communication with...""
- **azure-ai-voicelive-ts**: "Azure AI Voice Live SDK for JavaScript/TypeScript. Build real-time voice AI applications with bidirectional WebSocket communication."
- **azure-appconfiguration-java**: "Azure App Configuration SDK for Java. Centralized application configuration management with key-value settings, feature flags, and snapshots."
- **azure-appconfiguration-py**: "Azure App Configuration SDK for Python. Use for centralized configuration management, feature flags, and dynamic settings."
- **azure-appconfiguration-ts**: ""Build applications using Azure App Configuration SDK for JavaScript (@azure/app-configuration). Use when working with configuration settings, feature flags, Key Vault references, dynamic refresh, o...""
- **azure-communication-callautomation-java**: ""Build call automation workflows with Azure Communication Services Call Automation Java SDK. Use when implementing IVR systems, call routing, call recording, DTMF recognition, text-to-speech, or AI-...""
- **azure-communication-callingserver-java**: ""Azure Communication Services CallingServer (legacy) Java SDK. Note - This SDK is deprecated. Use azure-communication-callautomation instead for new projects. Only use this skill when maintaining le...""
- **azure-communication-chat-java**: ""Build real-time chat applications with Azure Communication Services Chat Java SDK. Use when implementing chat threads, messaging, participants, read receipts, typing notifications, or real-time cha...""
- **azure-communication-common-java**: ""Azure Communication Services common utilities for Java. Use when working with CommunicationTokenCredential, user identifiers, token refresh, or shared authentication across ACS services.""
- **azure-communication-sms-java**: ""Send SMS messages with Azure Communication Services SMS Java SDK. Use when implementing SMS notifications, alerts, OTP delivery, bulk messaging, or delivery reports.""
- **azure-compute-batch-java**: "Azure Batch SDK for Java. Run large-scale parallel and HPC batch jobs with pools, jobs, tasks, and compute nodes."
- **azure-containerregistry-py**: "Azure Container Registry SDK for Python. Use for managing container images, artifacts, and repositories."
- **azure-cosmos-db-py**: ""Build Azure Cosmos DB NoSQL services with Python/FastAPI following production-grade patterns. Use when implementing database client setup with dual auth (DefaultAzureCredential + emulator), service...""
- **azure-cosmos-java**: "Azure Cosmos DB SDK for Java. NoSQL database operations with global distribution, multi-model support, and reactive patterns."
- **azure-cosmos-py**: "Azure Cosmos DB SDK for Python (NoSQL API). Use for document CRUD, queries, containers, and globally distributed data."
- **azure-cosmos-rust**: "Azure Cosmos DB SDK for Rust (NoSQL API). Use for document CRUD, queries, containers, and globally distributed data."
- **azure-cosmos-ts**: "Azure Cosmos DB JavaScript/TypeScript SDK (@azure/cosmos) for data plane operations. Use for CRUD operations on documents, queries, bulk operations, and container management."
- **azure-data-tables-java**: ""Build table storage applications with Azure Tables SDK for Java. Use when working with Azure Table Storage or Cosmos DB Table API for NoSQL key-value data, schemaless storage, or structured data at...""
- **azure-data-tables-py**: "Azure Tables SDK for Python (Storage and Cosmos DB). Use for NoSQL key-value storage, entity CRUD, and batch operations."
- **azure-eventgrid-dotnet**: "Azure Event Grid SDK for .NET. Client library for publishing and consuming events with Azure Event Grid. Use for event-driven architectures, pub/sub messaging, CloudEvents, and EventGridEvents."
- **azure-eventgrid-java**: ""Build event-driven applications with Azure Event Grid SDK for Java. Use when publishing events, implementing pub/sub patterns, or integrating with Azure services via events.""
- **azure-eventgrid-py**: "Azure Event Grid SDK for Python. Use for publishing events, handling CloudEvents, and event-driven architectures."
- **azure-eventhub-dotnet**: "Azure Event Hubs SDK for .NET."
- **azure-eventhub-java**: ""Build real-time streaming applications with Azure Event Hubs SDK for Java. Use when implementing event streaming, high-throughput data ingestion, or building event-driven architectures.""
- **azure-eventhub-py**: "Azure Event Hubs SDK for Python streaming. Use for high-throughput event ingestion, producers, consumers, and checkpointing."
- **azure-eventhub-rust**: "Azure Event Hubs SDK for Rust. Use for sending and receiving events, streaming data ingestion."
- **azure-eventhub-ts**: ""Build event streaming applications using Azure Event Hubs SDK for JavaScript (@azure/event-hubs). Use when implementing high-throughput event ingestion, real-time analytics, IoT telemetry, or event...""
- **azure-functions**: ""Expert patterns for Azure Functions development including isolated worker model, Durable Functions orchestration, cold start optimization, and production patterns. Covers .NET, Python, and Node.js ...""
- **azure-identity-dotnet**: "Azure Identity SDK for .NET. Authentication library for Azure SDK clients using Microsoft Entra ID. Use for DefaultAzureCredential, managed identity, service principals, and developer credentials."
- **azure-identity-java**: ""Azure Identity Java SDK for authentication with Azure services. Use when implementing DefaultAzureCredential, managed identity, service principal, or any Azure authentication pattern in Java applic...""
- **azure-identity-py**: "Azure Identity SDK for Python authentication. Use for DefaultAzureCredential, managed identity, service principals, and token caching."
- **azure-identity-rust**: "Azure Identity SDK for Rust authentication. Use for DeveloperToolsCredential, ManagedIdentityCredential, ClientSecretCredential, and token-based authentication."
- **azure-identity-ts**: ""Authenticate to Azure services using Azure Identity SDK for JavaScript (@azure/identity). Use when configuring authentication with DefaultAzureCredential, managed identity, service principals, or i...""
- **azure-keyvault-certificates-rust**: "Azure Key Vault Certificates SDK for Rust. Use for creating, importing, and managing certificates."
- **azure-keyvault-keys-rust**: "'Azure Key Vault Keys SDK for Rust. Use for creating, managing, and using cryptographic keys. Triggers: "keyvault keys rust", "KeyClient rust", "create key rust", "encrypt rust", "sign rust".'"
- **azure-keyvault-keys-ts**: ""Manage cryptographic keys using Azure Key Vault Keys SDK for JavaScript (@azure/keyvault-keys). Use when creating, encrypting/decrypting, signing, or rotating keys.""
- **azure-keyvault-py**: "Azure Key Vault SDK for Python. Use for secrets, keys, and certificates management with secure storage."
- **azure-keyvault-secrets-rust**: "'Azure Key Vault Secrets SDK for Rust. Use for storing and retrieving secrets, passwords, and API keys. Triggers: "keyvault secrets rust", "SecretClient rust", "get secret rust", "set secret rust".'"
- **azure-keyvault-secrets-ts**: ""Manage secrets using Azure Key Vault Secrets SDK for JavaScript (@azure/keyvault-secrets). Use when storing and retrieving application secrets or configuration values.""
- **azure-maps-search-dotnet**: "Azure Maps SDK for .NET. Location-based services including geocoding, routing, rendering, geolocation, and weather. Use for address search, directions, map tiles, IP geolocation, and weather data."
- **azure-messaging-webpubsub-java**: ""Build real-time web applications with Azure Web PubSub SDK for Java. Use when implementing WebSocket-based messaging, live updates, chat applications, or server-to-client push notifications.""
- **azure-messaging-webpubsubservice-py**: "Azure Web PubSub Service SDK for Python. Use for real-time messaging, WebSocket connections, and pub/sub patterns."
- **azure-mgmt-apicenter-dotnet**: "Azure API Center SDK for .NET. Centralized API inventory management with governance, versioning, and discovery."
- **azure-mgmt-apicenter-py**: "Azure API Center Management SDK for Python. Use for managing API inventory, metadata, and governance across your organization."
- **azure-mgmt-apimanagement-dotnet**: "Azure Resource Manager SDK for API Management in .NET."
- **azure-mgmt-apimanagement-py**: "Azure API Management SDK for Python. Use for managing APIM services, APIs, products, subscriptions, and policies."
- **azure-mgmt-applicationinsights-dotnet**: "Azure Application Insights SDK for .NET. Application performance monitoring and observability resource management."
- **azure-mgmt-arizeaiobservabilityeval-dotnet**: "Azure Resource Manager SDK for Arize AI Observability and Evaluation (.NET)."
- **azure-mgmt-botservice-dotnet**: "Azure Resource Manager SDK for Bot Service in .NET. Management plane operations for creating and managing Azure Bot resources, channels (Teams, DirectLine, Slack), and connection settings."
- **azure-mgmt-botservice-py**: "Azure Bot Service Management SDK for Python. Use for creating, managing, and configuring Azure Bot Service resources."
- **azure-mgmt-fabric-dotnet**: "Azure Resource Manager SDK for Fabric in .NET."
- **azure-mgmt-fabric-py**: "Azure Fabric Management SDK for Python. Use for managing Microsoft Fabric capacities and resources."
- **azure-mgmt-mongodbatlas-dotnet**: ""Manage MongoDB Atlas Organizations as Azure ARM resources using Azure.ResourceManager.MongoDBAtlas SDK. Use when creating, updating, listing, or deleting MongoDB Atlas organizations through Azure M...""
- **azure-mgmt-weightsandbiases-dotnet**: "Azure Weights & Biases SDK for .NET. ML experiment tracking and model management via Azure Marketplace. Use for creating W&B instances, managing SSO, marketplace integration, and ML observability."
- **azure-microsoft-playwright-testing-ts**: ""Run Playwright tests at scale using Azure Playwright Workspaces (formerly Microsoft Playwright Testing). Use when scaling browser tests across cloud-hosted browsers, integrating with CI/CD pipeline...""
- **azure-monitor-ingestion-java**: "Azure Monitor Ingestion SDK for Java. Send custom logs to Azure Monitor via Data Collection Rules (DCR) and Data Collection Endpoints (DCE)."
- **azure-monitor-ingestion-py**: "Azure Monitor Ingestion SDK for Python. Use for sending custom logs to Log Analytics workspace via Logs Ingestion API."
- **azure-monitor-opentelemetry-exporter-java**: "Azure Monitor OpenTelemetry Exporter for Java. Export OpenTelemetry traces, metrics, and logs to Azure Monitor/Application Insights."
- **azure-monitor-opentelemetry-exporter-py**: "Azure Monitor OpenTelemetry Exporter for Python. Use for low-level OpenTelemetry export to Application Insights."
- **azure-monitor-opentelemetry-py**: "Azure Monitor OpenTelemetry Distro for Python. Use for one-line Application Insights setup with auto-instrumentation."
- **azure-monitor-opentelemetry-ts**: ""Instrument applications with Azure Monitor and OpenTelemetry for JavaScript (@azure/monitor-opentelemetry). Use when adding distributed tracing, metrics, and logs to Node.js applications with Appli...""
- **azure-monitor-query-java**: "Azure Monitor Query SDK for Java. Execute Kusto queries against Log Analytics workspaces and query metrics from Azure resources."
- **azure-monitor-query-py**: "Azure Monitor Query SDK for Python. Use for querying Log Analytics workspaces and Azure Monitor metrics."
- **azure-postgres-ts**: "Connect to Azure Database for PostgreSQL Flexible Server from Node.js/TypeScript using the pg (node-postgres) package."
- **azure-resource-manager-cosmosdb-dotnet**: "Azure Resource Manager SDK for Cosmos DB in .NET."
- **azure-resource-manager-durabletask-dotnet**: "Azure Resource Manager SDK for Durable Task Scheduler in .NET."
- **azure-resource-manager-mysql-dotnet**: "Azure MySQL Flexible Server SDK for .NET. Database management for MySQL Flexible Server deployments."
- **azure-resource-manager-playwright-dotnet**: "Azure Resource Manager SDK for Microsoft Playwright Testing in .NET."
- **azure-resource-manager-postgresql-dotnet**: "Azure PostgreSQL Flexible Server SDK for .NET. Database management for PostgreSQL Flexible Server deployments."
- **azure-resource-manager-redis-dotnet**: "Azure Resource Manager SDK for Redis in .NET."
- **azure-resource-manager-sql-dotnet**: "Azure Resource Manager SDK for Azure SQL in .NET."
- **azure-search-documents-dotnet**: "Azure AI Search SDK for .NET (Azure.Search.Documents). Use for building search applications with full-text, vector, semantic, and hybrid search."
- **azure-search-documents-py**: "Azure AI Search SDK for Python. Use for vector search, hybrid search, semantic ranking, indexing, and skillsets."
- **azure-search-documents-ts**: ""Build search applications using Azure AI Search SDK for JavaScript (@azure/search-documents). Use when creating/managing indexes, implementing vector/hybrid search, semantic ranking, or building ag...""
- **azure-security-keyvault-keys-dotnet**: "Azure Key Vault Keys SDK for .NET. Client library for managing cryptographic keys in Azure Key Vault and Managed HSM. Use for key creation, rotation, encryption, decryption, signing, and verification."
- **azure-security-keyvault-keys-java**: ""Azure Key Vault Keys Java SDK for cryptographic key management. Use when creating, managing, or using RSA/EC keys, performing encrypt/decrypt/sign/verify operations, or working with HSM-backed keys.""
- **azure-security-keyvault-secrets-java**: ""Azure Key Vault Secrets Java SDK for secret management. Use when storing, retrieving, or managing passwords, API keys, connection strings, or other sensitive configuration data.""
- **azure-servicebus-dotnet**: "Azure Service Bus SDK for .NET. Enterprise messaging with queues, topics, subscriptions, and sessions."
- **azure-servicebus-py**: "Azure Service Bus SDK for Python messaging. Use for queues, topics, subscriptions, and enterprise messaging patterns."
- **azure-servicebus-ts**: ""Build messaging applications using Azure Service Bus SDK for JavaScript (@azure/service-bus). Use when implementing queues, topics/subscriptions, message sessions, dead-letter handling, or enterpri...""
- **azure-speech-to-text-rest-py**: "Azure Speech to Text REST API for short audio (Python). Use for simple speech recognition of audio files up to 60 seconds without the Speech SDK."
- **azure-storage-blob-java**: ""Build blob storage applications with Azure Storage Blob SDK for Java. Use when uploading, downloading, or managing files in Azure Blob Storage, working with containers, or implementing streaming da...""
- **azure-storage-blob-py**: "Azure Blob Storage SDK for Python. Use for uploading, downloading, listing blobs, managing containers, and blob lifecycle."
- **azure-storage-blob-rust**: "Azure Blob Storage SDK for Rust. Use for uploading, downloading, and managing blobs and containers."
- **azure-storage-blob-ts**: "Azure Blob Storage JavaScript/TypeScript SDK (@azure/storage-blob) for blob operations. Use for uploading, downloading, listing, and managing blobs and containers."
- **azure-storage-file-datalake-py**: "Azure Data Lake Storage Gen2 SDK for Python. Use for hierarchical file systems, big data analytics, and file/directory operations."
- **azure-storage-file-share-py**: "Azure Storage File Share SDK for Python. Use for SMB file shares, directories, and file operations in the cloud."
- **azure-storage-file-share-ts**: "Azure File Share JavaScript/TypeScript SDK (@azure/storage-file-share) for SMB file share operations."
- **azure-storage-queue-py**: "Azure Queue Storage SDK for Python. Use for reliable message queuing, task distribution, and asynchronous processing."
- **azure-storage-queue-ts**: "Azure Queue Storage JavaScript/TypeScript SDK (@azure/storage-queue) for message queue operations. Use for sending, receiving, peeking, and deleting messages in queues."
- **azure-web-pubsub-ts**: ""Build real-time messaging applications using Azure Web PubSub SDKs for JavaScript (@azure/web-pubsub, @azure/web-pubsub-client). Use when implementing WebSocket-based real-time features, pub/sub me...""
- **copilot-sdk**: ""Build applications powered by GitHub Copilot using the Copilot SDK. Use when creating programmatic integrations with Copilot across Node.js/TypeScript, Python, Go, or .NET. Covers session managemen...""
- **m365-agents-dotnet**: "Microsoft 365 Agents SDK for .NET. Build multichannel agents for Teams/M365/Copilot Studio with ASP.NET Core hosting, AgentApplication routing, and MSAL-based auth."
- **m365-agents-py**: "Microsoft 365 Agents SDK for Python. Build multichannel agents for Teams/M365/Copilot Studio with aiohttp hosting, AgentApplication routing, streaming responses, and MSAL-based auth."
- **m365-agents-ts**: "Microsoft 365 Agents SDK for TypeScript/Node.js."
- **mcp-builder-ms**: ""Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate exte...""
- **microsoft-azure-webjobs-extensions-authentication-events-dotnet**: "Microsoft Entra Authentication Events SDK for .NET. Azure Functions triggers for custom authentication extensions."


## 🧠 Behavior
1. **Analyze & Match:** Connect user intent to the skills listed above.
2. **Read the File:** Before writing code, use your file reading tools to explicitly read the `SKILL.md` file from `.cursor/skills/[skill-name]/SKILL.md` or `.claude/skills/[skill-name]/SKILL.md`.
3. **Execute Transparently:** Apply the rules learned from the skill file seamlessly.
4. **Limits:** Keep context concise—only load 1-5 max skills per task.
